#!/bin/zsh

c () {
    if [[ $# -eq 1 ]]; then
        cd "$PROJECTS/$1"
    elif [[ -f $HOME/.current-project ]]; then
        local project=`cat $HOME/.current-project`
        if [[ -d $project ]]; then
            cd "$project"
        fi
    fi
}
